=== squaregoldfish/LongWebcam/web/longwebcam/resources/xml/image_upload.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.longwebcam.org/xml/upload" xmlns="http://www.longwebcam.org/xml/upload" elementFormDefault="qualified">
  <xs:element name="image_upload">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="camera"/>
        <xs:element ref="image"/>
        <xs:element ref="weather"  minOccurs="0" maxOccurs="1"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="camera">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="id" type="xs:string"/>
        <xs:element name="code" type="xs:string"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="image">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="date" type="xs:string"/>
        <xs:element name="file_data" type="xs:string"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="weather">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="time" type="xs:string"/>
        <xs:element name="temperature" type="xs:integer"/>
        <xs:element name="weather_code" type="xs:integer"/>
        <xs:element name="wind_speed" type="xs:integer"/>
        <xs:element name="wind_bearing" type="xs:integer"/>
        <xs:element name="rain" type="xs:integer"/>
        <xs:element name="visibility" type="xs:integer"/>
        <xs:element name="pressure" type="xs:integer"/>
        <xs:element name="cloud_cover" type="xs:integer"/>
        <xs:element name="air_quality" type="xs:integer"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== squaregoldfish/LongWebcam/web/longwebcam/resources/xml/image_upload.sample.xml
<?xml version="1.0" encoding="UTF-8"?>
<image_upload xmlns="http://www.longwebcam.org/xml/upload" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.longwebcam.org/xml/upload image_upload.xsd">
  <camera>
    <id>1</id>
    <code>6067</code>
  </camera>
  <image>
    <date>2013-01-01T01:01:01+00:00</date>
    <file_data>Base64'd image data</file_data>
  </image>
  <weather>
    <time>2013-01-01T01:01:01+00:00</time>
    <temperature>29</temperature>
    <weather_code>102</weather_code>
    <wind_speed>5</wind_speed>
    <wind_bearing>231</wind_bearing>
    <rain>0</rain>
    <visibility>9999</visibility>
    <pressure>1003</pressure>
    <cloud_cover>90</cloud_cover>
    <air_quality>-1</air_quality>
  </weather>
</image_upload>
